### ISSUE TITLE
g!approve if Already has role then don't throw error

### ISSUE THREAD

**Issue by Groove-Theory** [Groove-Theory/Groovebot#127]
DiscordAPIError: Invalid Form Body
roles[1]: The set already contains this value
    at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
    at then (/app/node_modules/snekfetch/src/index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Groove-Theory** [comment]
Fixed with hotfix
