### ISSUE TITLE
Ranks Error on Print-All if rank does not exist

### ISSUE THREAD

**Issue by Groove-Theory** [Groove-Theory/Groovebot#90]
Make category

Make ranks by roles

Delete the role but not the rank

Print-all ---> crash
TypeError: Cannot read property 'name' of null
    at Object.exports.PrintRanks [as fFunc] (/app/js/Ranks.js:392:47)
    at process._tickCallback (internal/process/next_tick.js:68:7)

We need a deleteRole event that delete's the ID from the DB, also to skip a role if we can't find it from DB to Discord

**Comment by Groove-Theory** [comment]
https://github.com/Groove-Theory/Groovebot/pull/96

**Comment by Groove-Theory** [comment]
g!rank rank with space

This will break

Also need to have the skip function on bad IDs (or auto-delete them?)
